<?php
/**
 * Capitularia Meta Search global functions
 *
 * @package Capitularia_Meta_Search
 */

namespace cceh\capitularia\meta_search;

use \cceh\capitularia\lib;

/**
 * Should we perform a meta search?
 *
 * @return boolean True if this is a meta search.
 */

function is_meta_search ()
{
    return !is_admin () && array_key_exists ('s', $_GET);
}

/**
 * Should we highlight search results?
 *
 * @return boolean
 */

function is_highlight ()
{
    $highlight = $_GET[HIGHLIGHT] ?? $_GET['s'] ?? '';
    return !is_admin () && !empty ($highlight);
}

/**
 * Add current namespace
 *
 * @param string $function_name The class or function name without namespace
 *
 * @return string Name with namespace
 */

function ns ($function_name)
{
    return __NAMESPACE__ . '\\' . $function_name;
}

/**
 * Sanitize a text filed.
 *
 * @param string $text The text to sanitize.
 *
 * @return string The sanitized text.
 */

function sanitize ($text)
{
    return empty ($text) ? '' : strip_tags ($text);
}

/**
 * Get a list of all capitulars
 *
 * @return string[] All capitulars
 */

function get_capitulars ()
{
    $res = [];
    foreach (lib\api_json_request ('/data/capitularies.json/', array (), true) as $r) {
        $cap_id = $r['cap_id'];
        $transcriptions = $r['transcriptions'];
        if ($transcriptions > 1 && preg_match ('/^BK|^Mordek/', $cap_id)) {
            $res[] = $cap_id;
        }
    }
    return $res;
}

/**
 * Register the translations.
 *
 * @return void
 */

function on_init ()
{
    lib\load_textdomain (DOMAIN);
}

/**
 * Register the widget with Wordpress.
 *
 * @return void
 */

function on_widgets_init ()
{
    register_widget (ns ('Widget'));
}

/**
 * Add our custom HTTP query vars
 *
 * @param array $vars The stock query vars
 *
 * @return array The stock and custom query vars
 */

function on_query_vars ($vars)
{
    $vars[] = 'capit';
    $vars[] = 'place';
    $vars[] = 'notbefore';
    $vars[] = 'notafter';
    $vars[] = 'places';     // array of geonames ids
    $vars[] = 'placenames'; // array of names, used by 'You searched for: X'
    $vars[] = HIGHLIGHT;
    return $vars;
}

/**
 * Get the permalink for the search result
 *
 * Called from the search results page of the Capitularia theme.  Return a link that
 * will go to the post *and* highlight the search terms if followed.
 *
 * @param string $permalink The permalink generated by Wordpress
 *
 * @return string The decorated permalink
 */

function on_cap_meta_search_the_permalink ($permalink)
{
    $highlight = $_GET['s'] ?? '';
    if (!empty ($highlight)) {
        return esc_attr (add_query_arg (HIGHLIGHT, $highlight, $permalink));
    }
    return $permalink;
}

/**
 * Makes Wordpress display our custom search page.
 */

function on_template_include ($template)
{
    global $wp_query;
    if (!$wp_query->is_search) {
        return $template;
    }

    return dirname ( __FILE__ ) . '/search.php';
}

/**
 * Enqueue the front page script and localize it.
 *
 * The script is a webpacked Vue.js application containing its own css.
 *
 * @return void
 */

 function enqueue_scripts ()
 {
     $handle = 'cap-meta-search-front';

     lib\enqueue_from_manifest ("$handle.js", ['cap-theme-front.js']);

     lib\enqueue_from_manifest ("$handle.css");

     lib\wp_set_script_translations ("$handle.js", DOMAIN);
 }
