default:

    # see vendor/halleck45/phpmetrics/src/Hal/Application/Rule/DefaultRuleSet.php
    rules:
        commentWeight:        [   0,  30, 40   ]
        cyclomaticComplexity: [ 100,  50, 15   ]
        lcom:                 [   4,   2,  1.5 ]
        maintainabilityIndex: [   0,  65, 85   ]

    path:
        directory:   .
        extensions:  php
        exclude:     node_modules|tools|scripts|vendor

    template:
        title:       Capitularia

    logging:
        report:
            xml:     tools/reports/phpmetrics/phpmetrics.xml
            html:    tools/reports/phpmetrics/index.html
            csv:     tools/reports/phpmetrics/phpmetrics.csv
        violations:
            xml:     tools/reports/phpmetrics/violations.xml
        chart:
            bubbles: tools/reports/phpmetrics/bubbles.svg
